### ISSUE TITLE
Apogée - récupération prénom et sexe état civil

### ISSUE THREAD

**Issue by DidierUCA** [EsupPortail/esup-siscol#4]
Bonjour,

Comme indiqué dans le ticket (fait au mauvais endroit) : https://github.com/EsupPortail/esup-stage/issues/114

Il faudrait que le connecteur Apogée remonte les informations de l'**état civil** (et pas forcément ni prénom ni sexe d'usage).

Je suppose que la méthode utilisée est recupererInfosAdmEtu_v3, il existe dans les champs le "prénom état civil" ainsi que le "sexe état civil". On a besoin de ces éléments pour créer la convention (et qu'elle soit valide juridiquement).

Cordialement,
D. Chabaud

**Comment by acheraga** [comment]
Bonjour
 j'ai ajouté les champs "prénom état civil" ainsi que le "sexe état civil"
ils sont visibles via les endpoints: /apogee/infosAdmEtu et /apogee/etudiantRef
les ajouts ne sont commité que sur la branche DEV, après validation ça sera commié sur la branche main
Cordialement
